# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5b4176a1d6e8792532d7124aaaebea777de98f2c2103f9d8258722b2e837826b3bb3ff918e3e099dedcb00820376ff85c6187dca93834b1f26c9ab766d8d050
  stripe_public_key: pk_test_6Pis3aRYXCMPRTY7cR40rPXy
  stripe_private_key: sk_test_DBbfhkIFmcyICu08qPMnsWlS 
test:
  secret_key_base: 50c43871e7b08f94fac8d97d50a514cc33787b2367706402709010b0874f9637cbefecf6aafe1e64cf9a5307f01578ac58d3f52cdb3b943c707354c8c3a1b742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>
